import { Difficulty, Country } from "./types";

const allCountries: Country[] = [
    {"name": "Afghanistan", "code": "AF", difficulty: Difficulty.MEDIUM},
    {"name": "Albania", "code": "AL", difficulty: Difficulty.HARD},
    {"name": "Algeria", "code": "DZ", difficulty: Difficulty.HARD},
    {"name": "AndorrA", "code": "AD", difficulty: Difficulty.HARD},
    {"name": "Angola", "code": "AO", difficulty: Difficulty.HARD},
    {"name": "Antarctica", "code": "AQ", difficulty: Difficulty.EASY},
    {"name": "Argentina", "code": "AR", difficulty: Difficulty.MEDIUM},
    {"name": "Armenia", "code": "AM", difficulty: Difficulty.HARD},
    {"name": "Australia", "code": "AU", difficulty: Difficulty.EASY},
    {"name": "Austria", "code": "AT", difficulty: Difficulty.MEDIUM},
    {"name": "Azerbaijan", "code": "AZ", difficulty: Difficulty.EXPERT},
    {"name": "Bahamas", "code": "BS", difficulty: Difficulty.EXPERT},
    {"name": "Bahrain", "code": "BH", difficulty: Difficulty.HARD},
    {"name": "Bangladesh", "code": "BD", difficulty: Difficulty.EXPERT},
    {"name": "Barbados", "code": "BB", difficulty: Difficulty.EXPERT},
    {"name": "Belarus", "code": "BY", difficulty: Difficulty.HARD},
    {"name": "Belgium", "code": "BE", difficulty: Difficulty.MEDIUM},
    {"name": "Belize", "code": "BZ", difficulty: Difficulty.EXPERT},
    {"name": "Benin", "code": "BJ", difficulty: Difficulty.EXPERT},
    {"name": "Bhutan", "code": "BT", difficulty: Difficulty.EXPERT},
    {"name": "Bolivia", "code": "BO", difficulty: Difficulty.EXPERT},
    {"name": "Bosnia and Herzegovina", "code": "BA", difficulty: Difficulty.EXPERT},
    {"name": "Botswana", "code": "BW", difficulty: Difficulty.EXPERT},
    {"name": "Brazil", "code": "BR", difficulty: Difficulty.HARD},
    {"name": "Brunei Darussalam", "code": "BN", difficulty: Difficulty.EXPERT},
    {"name": "Bulgaria", "code": "BG", difficulty: Difficulty.HARD},
    {"name": "Burkina Faso", "code": "BF", difficulty: Difficulty.EXPERT},
    {"name": "Burundi", "code": "BI", difficulty: Difficulty.EXPERT},
    {"name": "Cambodia", "code": "KH", difficulty: Difficulty.EXPERT},
    {"name": "Cameroon", "code": "CM", difficulty: Difficulty.EXPERT},
    {"name": "Canada", "code": "CA", difficulty: Difficulty.MEDIUM},
    {"name": "Cape Verde", "code": "CV", difficulty: Difficulty.EXPERT},
    {"name": "Central African Republic", "code": "CF", difficulty: Difficulty.EXPERT},
    {"name": "Chad", "code": "TD", difficulty: Difficulty.EXPERT},
    {"name": "Chile", "code": "CL", difficulty: Difficulty.HARD},
    {"name": "China", "code": "CN", difficulty: Difficulty.EASY},
    {"name": "Colombia", "code": "CO", difficulty: Difficulty.HARD},
    {"name": "Comoros", "code": "KM", difficulty: Difficulty.EXPERT},
    {"name": "Congo", "code": "CG", difficulty: Difficulty.EXPERT},
    {"name": "Costa Rica", "code": "CR", difficulty: Difficulty.MEDIUM},
    {"name": "Croatia", "code": "HR", difficulty: Difficulty.HARD},
    {"name": "Cuba", "code": "CU", difficulty: Difficulty.EXPERT},
    {"name": "Cyprus", "code": "CY", difficulty: Difficulty.MEDIUM},
    {"name": "Czech Republic", "code": "CZ", difficulty: Difficulty.MEDIUM},
    {"name": "Denmark", "code": "DK", difficulty: Difficulty.EASY},
    {"name": "Dominica", "code": "DM", difficulty: Difficulty.EXPERT},
    {"name": "Ecuador", "code": "EC", difficulty: Difficulty.EXPERT},
    {"name": "Egypt", "code": "EG", difficulty: Difficulty.EASY},
    {"name": "El Salvador", "code": "SV", difficulty: Difficulty.HARD},
    {"name": "Eritrea", "code": "ER", difficulty: Difficulty.EXPERT},
    {"name": "Estonia", "code": "EE", difficulty: Difficulty.EXPERT},
    {"name": "Ethiopia", "code": "ET", difficulty: Difficulty.MEDIUM},
    {"name": "Fiji", "code": "FJ", difficulty: Difficulty.EXPERT},
    {"name": "Finland", "code": "FI", difficulty: Difficulty.EASY},
    {"name": "France", "code": "FR", difficulty: Difficulty.EASY},
    {"name": "Gabon", "code": "GA", difficulty: Difficulty.EXPERT},
    {"name": "Gambia", "code": "GM", difficulty: Difficulty.EXPERT},
    {"name": "Georgia", "code": "GE", difficulty: Difficulty.HARD},
    {"name": "Germany", "code": "DE", difficulty: Difficulty.EASY},
    {"name": "Ghana", "code": "GH", difficulty: Difficulty.EXPERT},
    {"name": "Greece", "code": "GR", difficulty: Difficulty.EASY},
    {"name": "Greenland", "code": "GL", difficulty: Difficulty.MEDIUM},
    {"name": "Guatemala", "code": "GT", difficulty: Difficulty.HARD},
    {"name": "Guinea", "code": "GN", difficulty: Difficulty.EXPERT},
    {"name": "Haiti", "code": "HT", difficulty: Difficulty.EXPERT},
    {"name": "Honduras", "code": "HN", difficulty: Difficulty.EXPERT},
    {"name": "Hong Kong", "code": "HK", difficulty: Difficulty.MEDIUM},
    {"name": "Hungary", "code": "HU", difficulty: Difficulty.MEDIUM},
    {"name": "Iceland", "code": "IS", difficulty: Difficulty.EASY},
    {"name": "India", "code": "IN", difficulty: Difficulty.EASY},
    {"name": "Indonesia", "code": "ID", difficulty: Difficulty.MEDIUM},
    {"name": "Iran", "code": "IR", difficulty: Difficulty.EASY},
    {"name": "Iraq", "code": "IQ", difficulty: Difficulty.MEDIUM},
    {"name": "Ireland", "code": "IE", difficulty: Difficulty.MEDIUM},
    {"name": "Isle of Man", "code": "IM", difficulty: Difficulty.EXPERT},
    {"name": "Israel", "code": "IL", difficulty: Difficulty.EASY},
    {"name": "Italy", "code": "IT", difficulty: Difficulty.EASY},
    {"name": "Jamaica", "code": "JM", difficulty: Difficulty.HARD},
    {"name": "Japan", "code": "JP", difficulty: Difficulty.EASY},
    {"name": "Jordan", "code": "JO", difficulty: Difficulty.EASY},
    {"name": "Kazakhstan", "code": "KZ", difficulty: Difficulty.HARD},
    {"name": "Kenya", "code": "KE", difficulty: Difficulty.EXPERT},
    {"name": "North Korea", "code": "KP", difficulty: Difficulty.EASY},
    {"name": "South Korea", "code": "KR", difficulty: Difficulty.MEDIUM},
    {"name": "Kuwait", "code": "KW", difficulty: Difficulty.EXPERT},
    {"name": "Kyrgyzstan", "code": "KG", difficulty: Difficulty.EXPERT},
    {"name": "Latvia", "code": "LV", difficulty: Difficulty.EXPERT},
    {"name": "Lebanon", "code": "LB", difficulty: Difficulty.EASY},
    {"name": "Liberia", "code": "LR", difficulty: Difficulty.EXPERT},
    {"name": "Liechtenstein", "code": "LI", difficulty: Difficulty.EXPERT},
    {"name": "Lithuania", "code": "LT", difficulty: Difficulty.EXPERT},
    {"name": "Luxembourg", "code": "LU", difficulty: Difficulty.EXPERT},
    {"name": "Macedonia", "code": "MK", difficulty: Difficulty.EXPERT},
    {"name": "Madagascar", "code": "MG", difficulty: Difficulty.HARD},
    {"name": "Malawi", "code": "MW", difficulty: Difficulty.EXPERT},
    {"name": "Malaysia", "code": "MY", difficulty: Difficulty.EXPERT},
    {"name": "Maldives", "code": "MV", difficulty: Difficulty.MEDIUM},
    {"name": "Mali", "code": "ML", difficulty: Difficulty.EXPERT},
    {"name": "Malta", "code": "MT", difficulty: Difficulty.EXPERT},
    {"name": "Marshall Islands", "code": "MH", difficulty: Difficulty.EXPERT},
    {"name": "Mauritius", "code": "MU", difficulty: Difficulty.EXPERT},
    {"name": "Mexico", "code": "MX", difficulty: Difficulty.MEDIUM},
    {"name": "Moldova", "code": "MD", difficulty: Difficulty.EXPERT},
    {"name": "Monaco", "code": "MC", difficulty: Difficulty.EXPERT},
    {"name": "Mongolia", "code": "MN", difficulty: Difficulty.EXPERT},
    {"name": "Morocco", "code": "MA", difficulty: Difficulty.HARD},
    {"name": "Nauru", "code": "NR", difficulty: Difficulty.EXPERT},
    {"name": "Nepal", "code": "NP", difficulty: Difficulty.EXPERT},
    {"name": "Netherlands", "code": "NL", difficulty: Difficulty.EASY},
    {"name": "New Caledonia", "code": "NC", difficulty: Difficulty.EXPERT},
    {"name": "New Zealand", "code": "NZ", difficulty: Difficulty.EASY},
    {"name": "Nicaragua", "code": "NI", difficulty: Difficulty.EXPERT},
    {"name": "Niger", "code": "NE", difficulty: Difficulty.HARD},
    {"name": "Nigeria", "code": "NG", difficulty: Difficulty.HARD},
    {"name": "Norway", "code": "NO", difficulty: Difficulty.EASY},
    {"name": "Oman", "code": "OM", difficulty: Difficulty.EXPERT},
    {"name": "Pakistan", "code": "PK", difficulty: Difficulty.MEDIUM},
    {"name": "Palau", "code": "PW", difficulty: Difficulty.EXPERT},
    {"name": "Palestine", "code": "PS", difficulty: Difficulty.EASY},
    {"name": "Panama", "code": "PA", difficulty: Difficulty.EXPERT},
    {"name": "Paraguay", "code": "PY", difficulty: Difficulty.EXPERT},
    {"name": "Peru", "code": "PE", difficulty: Difficulty.HARD},
    {"name": "Philippines", "code": "PH", difficulty: Difficulty.HARD},
    {"name": "Pitcairn", "code": "PN", difficulty: Difficulty.EXPERT},
    {"name": "Poland", "code": "PL", difficulty: Difficulty.EASY},
    {"name": "Portugal", "code": "PT", difficulty: Difficulty.EASY},
    {"name": "Puerto Rico", "code": "PR", difficulty: Difficulty.HARD},
    {"name": "Qatar", "code": "QA", difficulty: Difficulty.MEDIUM},
    {"name": "Reunion", "code": "RE", difficulty: Difficulty.EXPERT},
    {"name": "Romania", "code": "RO", difficulty: Difficulty.EXPERT},
    {"name": "Russia", "code": "RU", difficulty: Difficulty.EASY},
    {"name": "RWANDA", "code": "RW", difficulty: Difficulty.EXPERT},
    {"name": "Samoa", "code": "WS", difficulty: Difficulty.EXPERT},
    {"name": "San Marino", "code": "SM", difficulty: Difficulty.EXPERT},
    {"name": "Sao Tome and Principe", "code": "ST", difficulty: Difficulty.EXPERT},
    {"name": "Saudi Arabia", "code": "SA", difficulty: Difficulty.MEDIUM},
    {"name": "Senegal", "code": "SN", difficulty: Difficulty.HARD},
    {"name": "Serbia", "code": "RS", difficulty: Difficulty.HARD},
    {"name": "Seychelles", "code": "SC", difficulty: Difficulty.MEDIUM},
    {"name": "Sierra Leone", "code": "SL", difficulty: Difficulty.EXPERT},
    {"name": "Singapore", "code": "SG", difficulty: Difficulty.MEDIUM},
    {"name": "Slovakia", "code": "SK", difficulty: Difficulty.EXPERT},
    {"name": "Slovenia", "code": "SI", difficulty: Difficulty.EXPERT},
    {"name": "Somalia", "code": "SO", difficulty: Difficulty.EXPERT},
    {"name": "South Africa", "code": "ZA", difficulty: Difficulty.MEDIUM},
    {"name": "Spain", "code": "ES", difficulty: Difficulty.EASY},
    {"name": "Sri Lanka", "code": "LK", difficulty: Difficulty.MEDIUM},
    {"name": "Sudan", "code": "SD", difficulty: Difficulty.HARD},
    {"name": "Sweden", "code": "SE", difficulty: Difficulty.EASY},
    {"name": "Switzerland", "code": "CH", difficulty: Difficulty.EASY},
    {"name": "Syria", "code": "SY", difficulty: Difficulty.EASY},
    {"name": "Taiwan", "code": "TW", difficulty: Difficulty.HARD},
    {"name": "Tajikistan", "code": "TJ", difficulty: Difficulty.EXPERT},
    {"name": "Tanzania", "code": "TZ", difficulty: Difficulty.EXPERT},
    {"name": "Thailand", "code": "TH", difficulty: Difficulty.HARD},
    {"name": "Togo", "code": "TG", difficulty: Difficulty.EXPERT},
    {"name": "Tokelau", "code": "TK", difficulty: Difficulty.EXPERT},
    {"name": "Tonga", "code": "TO", difficulty: Difficulty.EXPERT},
    {"name": "Tunisia", "code": "TN", difficulty: Difficulty.EXPERT},
    {"name": "Turkey", "code": "TR", difficulty: Difficulty.MEDIUM},
    {"name": "Turkmenistan", "code": "TM", difficulty: Difficulty.EXPERT},
    {"name": "Tuvalu", "code": "TV", difficulty: Difficulty.EXPERT},
    {"name": "Uganda", "code": "UG", difficulty: Difficulty.EXPERT},
    {"name": "Ukraine", "code": "UA", difficulty: Difficulty.EASY},
    {"name": "United Arab Emirates", "code": "AE", difficulty: Difficulty.EASY},
    {"name": "United Kingdom", "code": "GB", difficulty: Difficulty.EASY},
    {"name": "United States", "code": "US", difficulty: Difficulty.EASY},
    {"name": "Uruguay", "code": "UY", difficulty: Difficulty.HARD},
    {"name": "Uzbekistan", "code": "UZ", difficulty: Difficulty.HARD},
    {"name": "Vanuatu", "code": "VU", difficulty: Difficulty.EXPERT},
    {"name": "Venezuela", "code": "VE", difficulty: Difficulty.EXPERT},
    {"name": "VietNam", "code": "VN", difficulty: Difficulty.HARD},
    {"name": "Virgin Islands", "code": "VG", difficulty: Difficulty.EXPERT},
    {"name": "Virgin Islands", "code": "VI", difficulty: Difficulty.EXPERT},
    {"name": "Wallis and Futuna", "code": "WF", difficulty: Difficulty.EXPERT},
    {"name": "Yemen", "code": "YE", difficulty: Difficulty.EXPERT},
    {"name": "Zambia", "code": "ZM", difficulty: Difficulty.EXPERT},
    {"name": "Zimbabwe", "code": "ZW", difficulty: Difficulty.EXPERT}
]

export default allCountries;